### ISSUE TITLE
Ne fonctionne pas sur Lineageos microg

### ISSUE THREAD

**Issue by ghost** [damiengo/WebsiteRSS#2]
Bonjour,

J'ai installé cette application via f-droid sur un Lineageos MicroG (sans les gapps donc) et le contenu de l'application reste irrémédiablement vide ...

J'ai bien le header et le menu, avec les différentes sections, mais les RSS ne se chargent pas.

Simon

**Comment by damiengo** [comment]
Bonjour,

Est-il possible de connaître la version d'Android concernée?

Merci,
Damien

**Comment by ghost** [comment]
Lineageos 16.0, Android 9

**Comment by ghost** [comment]
Je peux faire quelque chose pour aider ?

**Comment by damiengo** [comment]
Oui avec plaisir!
Un lancement de l'application depuis android studio permettrait de récupérer les logs d'erreur, et les poster en réponse de cette issue.

Merci bcp! 😃

**Comment by damiengo** [comment]
Corrected in version 1.2
