### ISSUE TITLE
Lien vers l'article sur le site de L'Equipe

### ISSUE THREAD

**Issue by edern-appere** [damiengo/WebsiteRSS#3]
Bonjour,
Dans la vue des articles, ce serait pratique de rajouter un lien vers l'article original sur le site de L'Equipe. Ce serait notamment utile pour pouvoir visionner les vidéos qui sont parfois associées aux articles.
Merci !

**Comment by damiengo** [comment]
Bonjour,

En effet cela peut être utile.
Je prévois cela pour la prochaine version 👍

**Comment by damiengo** [comment]
C'est ajouté dans la v1.4.
