### ISSUE TITLE
L'appli ne charge plus de contenus

### ISSUE THREAD

**Issue by edern-appere** [damiengo/WebsiteRSS#4]
Bonjour,

Depuis quelques jours l'appli ne charge plus de contenus. En cliquant sur l'une des catégories un message d'erreur s'affiche (cf. pièce jointe). 
![Screenshot_20201025-184841_Equipe_RSS](https://user-images.githubusercontent.com/24966218/97114861-44ad3c80-16f3-11eb-8328-2283be8c1fe0.png)

Pour info, j'utilise la version 1.5 de l'application, sur LineageOs 17.1 (Android 10).
J'ai vidé le cache de l'application mais ça ne semble pas résoudre le problème. Est ce que le flux RSS de l'Equipe aurait changé ?

Merci pour votre aide et merci pour l'application, super pratique !

**Comment by damiengo** [comment]
Bonjour,

En effet il y a eu un changement quelque part depuis quelques jours. Je regarde cela dès que possible.

**Comment by edern-appere** [comment]
Merci !

**Comment by damiengo** [comment]
Bonjour,

J'ai l'impression que c'est corrigé, sûrement une mise à jour côté lequipe.
