### ISSUE TITLE
Le chargement du fil tombe en timeout

### ISSUE THREAD

**Issue by CMSplumbear** [damiengo/WebsiteRSS#5]
**Describe the bug**
Depuis 2 ou 3 jours le fil RSS ne se charge plus. 

Le message d'erreur (v1.5 sur Android 11 en Wifi)

`failed to connect to www6.lequipe.fr/10.40.47.203(port 443) from /10.1.10.1 (port 41338) after 10000ms`

Curieusement le message est différent en 4G (`"connection reset`") ou sur un autre smartphone en Android 7 (`"connect timed out"`)

Le lien `http://www.lequipe.fr/rss/actu_rss.xml` renvoie "`307 Temporary Redirect`" vers "`https://www6.lequipe.fr/rss/actu_rss.xml`".
Or `www6.lequipe.fr`pointe sur 10.40.47.203 qui est une adresse privée, non routable (RFC1918), vraisemblablement une erreur de configuration du DNS. Peut-être une adresse interne, qui ne devrait pas être résolue par le DNS public.
En tous cas la résolution fonctionnait correctement il y a quelques jours.

Mais, les flux RSS actifs sont documentés sur cette page (dernière modif le 17 mars): 
`https://www.lequipe.fr/Tous-sports/Actualites/Les-flux-rss-de-l-equipe/1299546`
Par exemple le flux général est `https://dwh.lequipe.fr/api/edito/rss?path=/` 

Est ce la suite d'une migration? Si l'erreur persiste, ne faudrait il pas plutôt utiliser les flux documentés?

**To Reproduce**
Start the app

**Smartphone (please complete the following information):**
 - Device: Galaxy A50 / A3 2016 
 - OS: Android 11 / 7.0

**Comment by damiengo** [comment]
Bonjour @CMSplumbear ,

Merci beaucoup pour l'analyse complète. En effet les flux RSS ont changé d'adresse, je procède à la correction.

**Comment by damiengo** [comment]
J'ai corrigé le problème dans la version 1.6.
