### ISSUE TITLE
L'application de fonctionne plus sur Android < 7.1.1, message: java.security.cert.CertPathValidatorException: Trust anchor for certification path not found

### ISSUE THREAD

**Issue by CMSplumbear** [damiengo/WebsiteRSS#6]
**Describe the bug**
Pas vraiment un bug, mais pour information l'application de fonctionne plus sur Android < 7.1.1 depuis 3 jours à cause du certificat Let's Encrypt  qui vient d'être renouvelé.

On trouve l'explication et les références dans le post #2 de ce fil
https://community.letsencrypt.org/t/letsencrypt-certificates-fails-on-android-phones-running-android-7-or-older/205686/2

Comme indiqué ici https://community.letsencrypt.org/t/production-chain-changes/150739
le nouveau certificat utilise cette "chaîne de confiance"
    dwh.lequipe.fr  ← R3 ← ISRG Root X1 
au lieu de la chaîne (vraisemblablement utilisée pour le certificat précédent)
    dwh.lequipe.fr ← R3 ← ISRG Root X1 ← DST Root CA X3
mais qui de toute façon expirera en septembre 2024

On peut voir la chaîne de confiance dans ce rapport SSL Labs
https://www.ssllabs.com/ssltest/analyze.html?d=dwh.lequipe.fr&s=104.118.246.133
(déplier la section "Certification Paths")

Sauf à convaincre L'Équipe de regénérer un certificat pour repousser le problème en septembre... (mission impossible?),
je ne vois pas d'autre solution si on veut pouvoir continuer à utiliser l'application sur les terminaux Android < 7.1.1  que d'accepter le certificat sans vérification ou passer en http (et seulement sur Android < 7.1.1)

**To Reproduce**
Start de app on Android < 7.1.1

**Smartphone (please complete the following information):**
 - Galaxy A3 2016
 - Android 7.0

**Additional context**
Ce n'est qu'un problème avec le certificat Let's Encrypt. Il n'y a pas de problème de chiffrement car TLS 1.2 est toujours supporté par le serveur 

Merci beaucoup pour cette application vraiment très pratique, je m'en sers tous les jours (sur un Android 11 :-)

**Comment by CMSplumbear** [comment]
L'application refonctionne car le certificat a été regénéré avec cette fois les deux "chaînes de confiance"!

**Comment by damiengo** [comment]
Même si le bug est corrigé, merci bcp pour cette analyse détaillée !
